### ISSUE TITLE
uninitialized constant BLS_API::RawRequest::Net

### ISSUE THREAD

**Issue by mistergibson** [associatedpress/bls_api#1]
To reproduce:

client = BLS_API::Client.new(<my-api-key>)
data = client.get(:series_ids => ["LNS14000000"], :start_year => 2015, :end_year => 2015)
Traceback (most recent call last):
        4: from /usr/bin/irb:11:in `<main>'
        3: from (irb):4
        2: from /var/lib/gems/2.5.0/gems/bls_api-1.1.0/lib/bls_api/client.rb:73:in `get'
        1: from /var/lib/gems/2.5.0/gems/bls_api-1.1.0/lib/bls_api/raw_request.rb:58:in `make_api_request'
NameError (uninitialized constant BLS_API::RawRequest::Net)

**Comment by mistergibson** [comment]
Thanks - caught it after some snooping.
require 'net/http' @ raw_request.rb

**Comment by myersjustinc** [comment]
Just cut v1.1.1 and pushed it to RubyGems. Thanks for the report!
